# Generated by Django 6.0 on 2025-12-22 13:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(choices=[('personal', 'Personal Loan'), ('home', 'Home Loan'), ('car', 'Car Loan'), ('education', 'Education Loan'), ('business', 'Business Loan')], max_length=20)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(1000)])),
                ('tenure_months', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(360)])),
                ('interest_rate', models.DecimalField(decimal_places=2, default=8.5, max_digits=4)),
                ('age', models.IntegerField()),
                ('income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employment_type', models.CharField(choices=[('salaried', 'Salaried'), ('self_employed', 'Self Employed'), ('business', 'Business'), ('unemployed', 'Unemployed')], max_length=20)),
                ('employment_years', models.IntegerField(default=0)),
                ('credit_score', models.IntegerField(default=300, validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(850)])),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced')], max_length=10)),
                ('dependents', models.IntegerField(default=0)),
                ('debt_to_income_ratio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('loan_to_value_ratio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('under_review', 'Under Review')], default='pending', max_length=20)),
                ('predicted_status', models.CharField(blank=True, max_length=20)),
                ('risk_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('approval_probability', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
                ('reviewed_date', models.DateTimeField(blank=True, null=True)),
                ('decision_date', models.DateTimeField(blank=True, null=True)),
                ('purpose', models.TextField(blank=True)),
                ('existing_loans', models.IntegerField(default=0)),
                ('existing_loan_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-applied_date'],
            },
        ),
        migrations.CreateModel(
            name='CreditHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('ontime', 'On Time'), ('late', 'Late'), ('defaulted', 'Defaulted')], max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('loan_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.loanapplication')),
            ],
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('application', 'Application'), ('prediction', 'Prediction'), ('system', 'System'), ('error', 'Error')], max_length=20)),
                ('message', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
