# Generated by Django 5.0.6 on 2025-12-23 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='debt_to_income_ratio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='loan_to_value_ratio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
